// src/constants/actionTypes.js

export const UPDATE_EXCHANGE_AMOUNT = 'UPDATE_EXCHANGE_AMOUNT';
export const UPDATE_EXCHANGE_FROM = 'UPDATE_EXCHANGE_FROM';
export const UPDATE_EXCHANGE_TO = 'UPDATE_EXCHANGE_TO';
export const UPDATE_EXCHANGE_RATE = 'UPDATE_EXCHANGE_RATE';
export const UPDATE_EXCHANGE_PAIR = 'UPDATE_EXCHANGE_PAIR';
export const UPDATE_BALANCE = 'UPDATE_BALANCE';